import './globals.css'
import type { Metadata } from 'next'
import { Inter} from 'next/font/google'
import Navbar from './Navbar';
import "@radix-ui/themes/styles.css"
import {Theme} from "@radix-ui/themes"
import "./theme-config.css"


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: '...',
    description: '...'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <body>
        <Theme accentColor="blue"> 
        <Navbar/>
          <main className='p-5'>
            {children}
          </main>
        </Theme>
      </body>
    </html>
  )
}
